### ISSUE TITLE
making a copy of a file works, creating an alias/shortcut doesnt

### ISSUE THREAD

**Issue by stemiwe** [learnweb/moodle-repository_owncloud#28] opened 2017-11-22 15:19 UTC
another step ahead, another new problem :)

thanks to all the help here, the plugin works at our site now, and files are displayed, and i can make a copy of a file in a course, BUT

if I try to create an alias to a file:
![image](https://user-images.githubusercontent.com/13886080/33134856-1bb0373e-cfa1-11e7-8c4a-1d7e4e2d7d5e.png)

i get this message:
**A request to ownCloud has failed: Invalid response**
![image](https://user-images.githubusercontent.com/13886080/33134873-26c5e7e0-cfa1-11e7-8c73-5ec4197e7922.png)

any ideas?

**Comment by Dagefoerde** [comment] 2017-11-22 15:24
It's great to hear that things are working out, thanks for the feedback!

Are you using ownCloud or Nextcloud? Sadly, Nextcloud has a limitation that prevents our plugin from creating such links (see the note on "File linking" on https://moodle.org/plugins/repository_owncloud). We are waiting for Nextcloud to solve their issue. There is nothing that we can to from the plugin's side to mitigate this issue. When they get it fixed, this plugin will be able to create links right away, no changes necessary.

If you are using ownCloud then I'd need an error message from ownCloud's logs to try and track down the matter.

**Comment by Dagefoerde** [comment] 2018-01-29 13:24
Hi @webers-technikum-wien, I realised that in #24 I could see that you are using Nextcloud, so it is likely that this is the cause of your issue. Therefore I am closing it, but please feel free to reopen it if necessary. 

By the way, good news: Nextcloud are in the process of fixing it https://github.com/nextcloud/server/pull/7873.

**Closed as completed by Dagefoerde** 2018-01-29 13:24 UTC
