### ISSUE TITLE
"Link to file directly" or "Create an alias..."

### ISSUE THREAD

**Issue by admin-teametry** [learnweb/moodle-repository_owncloud#35] opened 2018-07-09 14:48 UTC
I'm unsure about the difference.

I use Moodle 3.5.1 with the latest version of the great plugin.
If I use "Link to file directly" every change to a text or image or changing the folder of a linked file in the Nextcloud folder will be represented in Moodle. So it is very flexible.

OK. The links are different, one like described directly to the file with the Nextcloud URL, the other as a Moodle link.
As far as I tested, changes to the source file are changed the file in Moodle with both methods also.

What exactly is the difference to "Create an Alias/Link...." 
Or, what is the best strategy?

Ah, OK I see. Aliases aren't restored in other Moodle's, if I transferred a course, direct links (clearly) yes. So, it is a Moodle behavior, not dependent on the NextCloud plugin.

So, my question is easy:
Is it the wanted behavior as I described it above? 

Thanks and best regards
Andreas

**Comment by Dagefoerde** [comment] 2018-07-10 08:13
Hi Andreas,
where is this difference visible? I am not quite sure which pages the terms you mentioned are coming from. Screenshots would be great! Thanks!

**Comment by NinaHerrmann** [comment] 2018-07-10 08:18
Hello Andreas, hello Jan,

I think Andreas means the difference between using the URL activity which creates a direct link and Uploading a File where you can choose to create a alias. We determined which can be used in the `supported_returntypes() ` function. 
If this is the case Moodle describes the difference as the following:

>  FILE_EXTERNAL (link file directly) - the file stays in the external repository and is accessed from there directly

> FILE_REFERENCE (creating alias/link) - the file may be cached locally, but is automatically synchronised, as required, with any changes to the external 
[Moodle Page](https://docs.moodle.org/dev/Repository_plugins#Administration_APIs)

I guess you are right about aliases not being restored in other Moodle's however, I never tested that. Most of the time the two options behave quite similar from a user perspective. 
We are planning to remove the FILE_REFERENCE (creating alias link) when implementing the feature of access controlled links #27.
Best Regards, 
Nina

**Comment by Dagefoerde** [comment] 2018-08-14 11:44
Hi Andreas, I think I now see what you mean. When you perform a backup on a course that contains an alias (mod_resource with alias/link), you see this message:

![notice](https://user-images.githubusercontent.com/432117/44089510-4f5eac54-9fc7-11e8-952d-64e78306484c.png)

Nevertheless, the reference is contained in the backup, and if I restore it into a **different** course on the **same** site the reference is actually restored (as hinted in the last line of the following screenshot, but the files also appear in the new course correctly):

![references restored](https://user-images.githubusercontent.com/432117/44089656-e7f52312-9fc7-11e8-8cd7-589e2c9138a8.png)

I was not aware of this behaviour, so thank you for raising it. However, I would consider this as intended behaviour, though, because it is possible that such references wouldn't work if restored on a different system anyway because of the tight integration with Nextcloud as a file storage.

Again, if restore happens on the same system, this problem is not relevant, so for most use cases this is all good.

Closing for now; please reopen if you meant something different! Thanks.

**Closed as completed by Dagefoerde** 2018-08-14 11:44 UTC
