### ISSUE TITLE
Link to a file not working (e.g. in Atto Editor)

### ISSUE THREAD

**Issue by glu000** [learnweb/moodle-repository_owncloud#34] opened 2018-06-24 21:38 UTC
I installed the latest version of the plugin v3.5-r1, Moodle Version 3.4.3+ (Build: 20180524), Nextcloud Version 13.0.4.0

Connection to Nextcloud works fine. If I select a file (e.g. a picture) as copy this works also fine.

However, if I select a file as Alias/Link to file is not embedded into Atto Editor. I checked the access.log from Apache and found out, that the URL seems to be OK. When I copy this URL to a new browser window, the file is downloaded successfully.  

In contrast to issue #30 there is no error message shown. The file (picture) is just not displayed. When I switch to HTML mode in Atto it shows the link:

`<img src="https://moodle.mydomain.de/draftfile.php/5/user/draft/573702844/filename.png" alt="" width="600" height="300" role="presentation" class="atto_image_button_text-bottom"><br></p>`

**Comment by Dagefoerde** [comment] 2018-06-25 07:38
Hi, thanks for your report. Since you are saying that downloading the file from the same URL works, but embedding does not, this issue sounds like a variant of issue #7. It is a known problem resulting from a security feature of Nextcloud (and ownCloud), which prevents files from being embedded in different websites. 

I am going to close this issue because it is a duplicate of #7, but I'd like you to add it as a comment there. Maybe it also helps to report this in the Nextcloud forums, because we might need a mechanism in Nextcloud to facilitate embedding things in Moodle. From our side there's nothing we can do.

**Closed as completed by Dagefoerde** 2018-06-25 07:38 UTC
